spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:mem:test


product.service.url: http://localhost:8091/api/v1/products/
user.service.url: http://localhost:8092/api/v1/users/
